/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LocationSegments, MatchResults, RouterHistory } from "@stencil/router";
import { MenuItem } from "./interfaces/MenuItem";
import { ExtendedHistoryType } from "./interfaces/ExtendedHistoryType";
import { BreadcrumbSegment } from "./interfaces/BreadcrumbSegment";
export namespace Components {
    interface DropdownRenderer {
        "active": boolean;
        "somethingChanged": boolean;
        "url": any;
    }
    interface EventExpandableRenderer {
        "active": boolean;
        "firstMenuChild": any;
        "history": RouterHistory;
        "item": any;
        "somethingChanged": boolean;
        "url": any;
    }
    interface ExpandableRenderer {
        "active": boolean;
        "firstMenuChild": any;
        "history": RouterHistory;
        "somethingChanged": boolean;
        "url": any;
    }
    interface MobileProfileRenderer {
        "userInfo": any;
    }
    interface PskAppMenu {
        "hamburgerMaxWidth"?: number;
        "historyType": ExtendedHistoryType;
        "itemRenderer"?: string;
        "menuItems"?: MenuItem[];
    }
    interface PskAppRoot {
        "controller": any;
        "disableSidebar": boolean;
    }
    interface PskAppRouter {
        "historyType": ExtendedHistoryType;
        "routesItems"?: MenuItem[];
    }
    interface PskBreadcrumbNavigator {
        "eventName": string | null;
        "segments": BreadcrumbSegment[];
    }
    interface PskButton {
        "buttonClass": string | null;
        "disabled": string | boolean;
        "doubleClickEventName": string | null;
        "eventData": any | null;
        "eventDispatcher": string | null;
        "eventName": string | null;
        "label": string | null;
        "touchEventName": string | null;
        "type": string;
    }
    interface PskButtonGroup {
        "classes": string | null;
        "icon": string | null;
        "iconColor": string | null;
        "label": string | null;
        "opened": boolean;
    }
    interface PskButtonLink {
        "eventData": any | null;
        "eventDispatcher": string | null;
        "eventName": string | null;
        "icon"?: string;
        "name"?: string;
        "page": string;
    }
    interface PskCard {
        "id": string;
        "title": string;
    }
    interface PskCondition {
        "condition": any | null;
    }
    interface PskContainer {
        "controllerName"?: string | null;
        "history": RouterHistory;
        "htmlFilePath"?: string | null;
        "parentCallback": Function | null;
    }
    interface PskControllerDescriptor {
        "title": string;
    }
    interface PskDefaultRenderer {
        "disableSidebar": boolean;
        "mobileLayout": boolean;
    }
    interface PskDetails {
        "eventData": any | null;
        "eventDispatcher": string | null;
        "eventName": string | null;
        "layout": string;
        "opened": boolean;
        "title": string;
    }
    interface PskEcho {
        "value": string | null;
    }
    interface PskEventDescriptor {
        "title": string;
    }
    interface PskExample {
        "title": string;
    }
    interface PskForEach {
        "dataViewModel"?: string | null;
    }
    interface PskGrid {
        "columns": number | null;
        "layout": string | null;
    }
    interface PskLayout {
        "alignContent": string | null;
        "alignContentX": string | null;
        "alignContentY": string | null;
        "alignItems": string | null;
        "alignItemsX": string | null;
        "alignItemsY": string | null;
        "autoColumns": string | null;
        "autoFlow": string | null;
        "autoRows": string | null;
        "columnGap": string | null;
        "columns": number | null;
        "gap": string | null;
        "rowGap": string | null;
        "rows": number | null;
        "templateColumns": string | null;
        "templateRows": string | null;
    }
    interface PskLayoutItem {
        "align": string | null;
        "alignX": string | null;
        "alignY": string | null;
        "column": string | null;
        "columnEnd": string | null;
        "columnStart": string | null;
        "row": string | null;
        "rowEnd": string | null;
        "rowStart": string | null;
    }
    interface PskLink {
        "chapter": string;
        "page": string;
        "tag": string;
    }
    interface PskList {
        "listType": string;
    }
    interface PskMenuItemRenderer {
        "active": boolean;
        "historyType": ExtendedHistoryType;
        "value": MenuItem;
    }
    interface PskMobile {
        "controllerName"?: string | null;
        "disableHeader": boolean;
        "disableSidebar": boolean;
        "enableBack": boolean;
        "history": RouterHistory;
        "title": string;
        "toggleOptions": (visible: any) => Promise<void>;
        "toggleSidebar": (visible: any) => Promise<void>;
    }
    interface PskPage {
        "badgeBackgroundColor": string;
        "badgeText": string;
        "badgeTextColor": string;
        "hasToc": boolean;
        "navigationTitle": string;
        "pageClass": string;
        "subTitle": string;
        "title": string;
        "tocTitle": string;
    }
    interface PskPageLoader {
        "pageUrl": string;
        "type": string;
    }
    interface PskPageNotFound {
        "basePath"?: string;
        "pageRenderer"?: string;
        "urlDestination"?: string;
    }
    interface PskPageNotFoundRenderer {
    }
    interface PskPropertyDescriptor {
        "title": string;
    }
    interface PskRouteRedirect {
        "history": RouterHistory;
        "url": any;
    }
    interface PskSsapp {
        "appName": string;
        "history": RouterHistory;
        "landingPath": string;
        "match": MatchResults;
        "params": string;
        "seed": string;
    }
    interface PskStyle {
        "src": string | null;
    }
    interface PskUserProfile {
        "profileRenderer": any;
        "userInfo": any;
    }
    interface PskUserProfileRenderer {
        "userInfo": any;
    }
    interface QueryPageLink {
        "activeClass": string;
        "anchorClass"?: string;
        "anchorId"?: string;
        "anchorRole"?: string;
        "anchorTabIndex"?: string;
        "anchorTitle"?: string;
        "ariaHaspopup"?: string;
        "ariaLabel"?: string;
        "ariaPosinset"?: string;
        "ariaSetsize"?: number;
        /**
          * Custom tag to use instead of an anchor
         */
        "custom": string;
        "exact": boolean;
        "history"?: RouterHistory;
        "location"?: LocationSegments;
        "strict": boolean;
        "url"?: string;
        "urlMatch"?: string;
    }
    interface QueryPagesRouter {
        "history": RouterHistory;
        "location": LocationSegments;
        "pages": MenuItem[];
        "redirectTo": string;
    }
    interface SidebarRenderer {
        "active": boolean;
        "historyType": ExtendedHistoryType;
        "value": MenuItem;
    }
}
declare global {
    interface HTMLDropdownRendererElement extends Components.DropdownRenderer, HTMLStencilElement {
    }
    var HTMLDropdownRendererElement: {
        prototype: HTMLDropdownRendererElement;
        new (): HTMLDropdownRendererElement;
    };
    interface HTMLEventExpandableRendererElement extends Components.EventExpandableRenderer, HTMLStencilElement {
    }
    var HTMLEventExpandableRendererElement: {
        prototype: HTMLEventExpandableRendererElement;
        new (): HTMLEventExpandableRendererElement;
    };
    interface HTMLExpandableRendererElement extends Components.ExpandableRenderer, HTMLStencilElement {
    }
    var HTMLExpandableRendererElement: {
        prototype: HTMLExpandableRendererElement;
        new (): HTMLExpandableRendererElement;
    };
    interface HTMLMobileProfileRendererElement extends Components.MobileProfileRenderer, HTMLStencilElement {
    }
    var HTMLMobileProfileRendererElement: {
        prototype: HTMLMobileProfileRendererElement;
        new (): HTMLMobileProfileRendererElement;
    };
    interface HTMLPskAppMenuElement extends Components.PskAppMenu, HTMLStencilElement {
    }
    var HTMLPskAppMenuElement: {
        prototype: HTMLPskAppMenuElement;
        new (): HTMLPskAppMenuElement;
    };
    interface HTMLPskAppRootElement extends Components.PskAppRoot, HTMLStencilElement {
    }
    var HTMLPskAppRootElement: {
        prototype: HTMLPskAppRootElement;
        new (): HTMLPskAppRootElement;
    };
    interface HTMLPskAppRouterElement extends Components.PskAppRouter, HTMLStencilElement {
    }
    var HTMLPskAppRouterElement: {
        prototype: HTMLPskAppRouterElement;
        new (): HTMLPskAppRouterElement;
    };
    interface HTMLPskBreadcrumbNavigatorElement extends Components.PskBreadcrumbNavigator, HTMLStencilElement {
    }
    var HTMLPskBreadcrumbNavigatorElement: {
        prototype: HTMLPskBreadcrumbNavigatorElement;
        new (): HTMLPskBreadcrumbNavigatorElement;
    };
    interface HTMLPskButtonElement extends Components.PskButton, HTMLStencilElement {
    }
    var HTMLPskButtonElement: {
        prototype: HTMLPskButtonElement;
        new (): HTMLPskButtonElement;
    };
    interface HTMLPskButtonGroupElement extends Components.PskButtonGroup, HTMLStencilElement {
    }
    var HTMLPskButtonGroupElement: {
        prototype: HTMLPskButtonGroupElement;
        new (): HTMLPskButtonGroupElement;
    };
    interface HTMLPskButtonLinkElement extends Components.PskButtonLink, HTMLStencilElement {
    }
    var HTMLPskButtonLinkElement: {
        prototype: HTMLPskButtonLinkElement;
        new (): HTMLPskButtonLinkElement;
    };
    interface HTMLPskCardElement extends Components.PskCard, HTMLStencilElement {
    }
    var HTMLPskCardElement: {
        prototype: HTMLPskCardElement;
        new (): HTMLPskCardElement;
    };
    interface HTMLPskConditionElement extends Components.PskCondition, HTMLStencilElement {
    }
    var HTMLPskConditionElement: {
        prototype: HTMLPskConditionElement;
        new (): HTMLPskConditionElement;
    };
    interface HTMLPskContainerElement extends Components.PskContainer, HTMLStencilElement {
    }
    var HTMLPskContainerElement: {
        prototype: HTMLPskContainerElement;
        new (): HTMLPskContainerElement;
    };
    interface HTMLPskControllerDescriptorElement extends Components.PskControllerDescriptor, HTMLStencilElement {
    }
    var HTMLPskControllerDescriptorElement: {
        prototype: HTMLPskControllerDescriptorElement;
        new (): HTMLPskControllerDescriptorElement;
    };
    interface HTMLPskDefaultRendererElement extends Components.PskDefaultRenderer, HTMLStencilElement {
    }
    var HTMLPskDefaultRendererElement: {
        prototype: HTMLPskDefaultRendererElement;
        new (): HTMLPskDefaultRendererElement;
    };
    interface HTMLPskDetailsElement extends Components.PskDetails, HTMLStencilElement {
    }
    var HTMLPskDetailsElement: {
        prototype: HTMLPskDetailsElement;
        new (): HTMLPskDetailsElement;
    };
    interface HTMLPskEchoElement extends Components.PskEcho, HTMLStencilElement {
    }
    var HTMLPskEchoElement: {
        prototype: HTMLPskEchoElement;
        new (): HTMLPskEchoElement;
    };
    interface HTMLPskEventDescriptorElement extends Components.PskEventDescriptor, HTMLStencilElement {
    }
    var HTMLPskEventDescriptorElement: {
        prototype: HTMLPskEventDescriptorElement;
        new (): HTMLPskEventDescriptorElement;
    };
    interface HTMLPskExampleElement extends Components.PskExample, HTMLStencilElement {
    }
    var HTMLPskExampleElement: {
        prototype: HTMLPskExampleElement;
        new (): HTMLPskExampleElement;
    };
    interface HTMLPskForEachElement extends Components.PskForEach, HTMLStencilElement {
    }
    var HTMLPskForEachElement: {
        prototype: HTMLPskForEachElement;
        new (): HTMLPskForEachElement;
    };
    interface HTMLPskGridElement extends Components.PskGrid, HTMLStencilElement {
    }
    var HTMLPskGridElement: {
        prototype: HTMLPskGridElement;
        new (): HTMLPskGridElement;
    };
    interface HTMLPskLayoutElement extends Components.PskLayout, HTMLStencilElement {
    }
    var HTMLPskLayoutElement: {
        prototype: HTMLPskLayoutElement;
        new (): HTMLPskLayoutElement;
    };
    interface HTMLPskLayoutItemElement extends Components.PskLayoutItem, HTMLStencilElement {
    }
    var HTMLPskLayoutItemElement: {
        prototype: HTMLPskLayoutItemElement;
        new (): HTMLPskLayoutItemElement;
    };
    interface HTMLPskLinkElement extends Components.PskLink, HTMLStencilElement {
    }
    var HTMLPskLinkElement: {
        prototype: HTMLPskLinkElement;
        new (): HTMLPskLinkElement;
    };
    interface HTMLPskListElement extends Components.PskList, HTMLStencilElement {
    }
    var HTMLPskListElement: {
        prototype: HTMLPskListElement;
        new (): HTMLPskListElement;
    };
    interface HTMLPskMenuItemRendererElement extends Components.PskMenuItemRenderer, HTMLStencilElement {
    }
    var HTMLPskMenuItemRendererElement: {
        prototype: HTMLPskMenuItemRendererElement;
        new (): HTMLPskMenuItemRendererElement;
    };
    interface HTMLPskMobileElement extends Components.PskMobile, HTMLStencilElement {
    }
    var HTMLPskMobileElement: {
        prototype: HTMLPskMobileElement;
        new (): HTMLPskMobileElement;
    };
    interface HTMLPskPageElement extends Components.PskPage, HTMLStencilElement {
    }
    var HTMLPskPageElement: {
        prototype: HTMLPskPageElement;
        new (): HTMLPskPageElement;
    };
    interface HTMLPskPageLoaderElement extends Components.PskPageLoader, HTMLStencilElement {
    }
    var HTMLPskPageLoaderElement: {
        prototype: HTMLPskPageLoaderElement;
        new (): HTMLPskPageLoaderElement;
    };
    interface HTMLPskPageNotFoundElement extends Components.PskPageNotFound, HTMLStencilElement {
    }
    var HTMLPskPageNotFoundElement: {
        prototype: HTMLPskPageNotFoundElement;
        new (): HTMLPskPageNotFoundElement;
    };
    interface HTMLPskPageNotFoundRendererElement extends Components.PskPageNotFoundRenderer, HTMLStencilElement {
    }
    var HTMLPskPageNotFoundRendererElement: {
        prototype: HTMLPskPageNotFoundRendererElement;
        new (): HTMLPskPageNotFoundRendererElement;
    };
    interface HTMLPskPropertyDescriptorElement extends Components.PskPropertyDescriptor, HTMLStencilElement {
    }
    var HTMLPskPropertyDescriptorElement: {
        prototype: HTMLPskPropertyDescriptorElement;
        new (): HTMLPskPropertyDescriptorElement;
    };
    interface HTMLPskRouteRedirectElement extends Components.PskRouteRedirect, HTMLStencilElement {
    }
    var HTMLPskRouteRedirectElement: {
        prototype: HTMLPskRouteRedirectElement;
        new (): HTMLPskRouteRedirectElement;
    };
    interface HTMLPskSsappElement extends Components.PskSsapp, HTMLStencilElement {
    }
    var HTMLPskSsappElement: {
        prototype: HTMLPskSsappElement;
        new (): HTMLPskSsappElement;
    };
    interface HTMLPskStyleElement extends Components.PskStyle, HTMLStencilElement {
    }
    var HTMLPskStyleElement: {
        prototype: HTMLPskStyleElement;
        new (): HTMLPskStyleElement;
    };
    interface HTMLPskUserProfileElement extends Components.PskUserProfile, HTMLStencilElement {
    }
    var HTMLPskUserProfileElement: {
        prototype: HTMLPskUserProfileElement;
        new (): HTMLPskUserProfileElement;
    };
    interface HTMLPskUserProfileRendererElement extends Components.PskUserProfileRenderer, HTMLStencilElement {
    }
    var HTMLPskUserProfileRendererElement: {
        prototype: HTMLPskUserProfileRendererElement;
        new (): HTMLPskUserProfileRendererElement;
    };
    interface HTMLQueryPageLinkElement extends Components.QueryPageLink, HTMLStencilElement {
    }
    var HTMLQueryPageLinkElement: {
        prototype: HTMLQueryPageLinkElement;
        new (): HTMLQueryPageLinkElement;
    };
    interface HTMLQueryPagesRouterElement extends Components.QueryPagesRouter, HTMLStencilElement {
    }
    var HTMLQueryPagesRouterElement: {
        prototype: HTMLQueryPagesRouterElement;
        new (): HTMLQueryPagesRouterElement;
    };
    interface HTMLSidebarRendererElement extends Components.SidebarRenderer, HTMLStencilElement {
    }
    var HTMLSidebarRendererElement: {
        prototype: HTMLSidebarRendererElement;
        new (): HTMLSidebarRendererElement;
    };
    interface HTMLElementTagNameMap {
        "dropdown-renderer": HTMLDropdownRendererElement;
        "event-expandable-renderer": HTMLEventExpandableRendererElement;
        "expandable-renderer": HTMLExpandableRendererElement;
        "mobile-profile-renderer": HTMLMobileProfileRendererElement;
        "psk-app-menu": HTMLPskAppMenuElement;
        "psk-app-root": HTMLPskAppRootElement;
        "psk-app-router": HTMLPskAppRouterElement;
        "psk-breadcrumb-navigator": HTMLPskBreadcrumbNavigatorElement;
        "psk-button": HTMLPskButtonElement;
        "psk-button-group": HTMLPskButtonGroupElement;
        "psk-button-link": HTMLPskButtonLinkElement;
        "psk-card": HTMLPskCardElement;
        "psk-condition": HTMLPskConditionElement;
        "psk-container": HTMLPskContainerElement;
        "psk-controller-descriptor": HTMLPskControllerDescriptorElement;
        "psk-default-renderer": HTMLPskDefaultRendererElement;
        "psk-details": HTMLPskDetailsElement;
        "psk-echo": HTMLPskEchoElement;
        "psk-event-descriptor": HTMLPskEventDescriptorElement;
        "psk-example": HTMLPskExampleElement;
        "psk-for-each": HTMLPskForEachElement;
        "psk-grid": HTMLPskGridElement;
        "psk-layout": HTMLPskLayoutElement;
        "psk-layout-item": HTMLPskLayoutItemElement;
        "psk-link": HTMLPskLinkElement;
        "psk-list": HTMLPskListElement;
        "psk-menu-item-renderer": HTMLPskMenuItemRendererElement;
        "psk-mobile": HTMLPskMobileElement;
        "psk-page": HTMLPskPageElement;
        "psk-page-loader": HTMLPskPageLoaderElement;
        "psk-page-not-found": HTMLPskPageNotFoundElement;
        "psk-page-not-found-renderer": HTMLPskPageNotFoundRendererElement;
        "psk-property-descriptor": HTMLPskPropertyDescriptorElement;
        "psk-route-redirect": HTMLPskRouteRedirectElement;
        "psk-ssapp": HTMLPskSsappElement;
        "psk-style": HTMLPskStyleElement;
        "psk-user-profile": HTMLPskUserProfileElement;
        "psk-user-profile-renderer": HTMLPskUserProfileRendererElement;
        "query-page-link": HTMLQueryPageLinkElement;
        "query-pages-router": HTMLQueryPagesRouterElement;
        "sidebar-renderer": HTMLSidebarRendererElement;
    }
}
declare namespace LocalJSX {
    interface DropdownRenderer {
        "active"?: boolean;
        "somethingChanged"?: boolean;
        "url"?: any;
    }
    interface EventExpandableRenderer {
        "active"?: boolean;
        "firstMenuChild"?: any;
        "history"?: RouterHistory;
        "item"?: any;
        "somethingChanged"?: boolean;
        "url"?: any;
    }
    interface ExpandableRenderer {
        "active"?: boolean;
        "firstMenuChild"?: any;
        "history"?: RouterHistory;
        "onSectionChange"?: (event: CustomEvent<any>) => void;
        "somethingChanged"?: boolean;
        "url"?: any;
    }
    interface MobileProfileRenderer {
        "userInfo"?: any;
    }
    interface PskAppMenu {
        "hamburgerMaxWidth"?: number;
        "historyType"?: ExtendedHistoryType;
        "itemRenderer"?: string;
        "menuItems"?: MenuItem[];
        "onGetHistoryType"?: (event: CustomEvent<any>) => void;
        "onMenuEvent"?: (event: CustomEvent<any>) => void;
        "onNeedMenuItems"?: (event: CustomEvent<any>) => void;
    }
    interface PskAppRoot {
        "controller"?: any;
        "disableSidebar"?: boolean;
    }
    interface PskAppRouter {
        "historyType"?: ExtendedHistoryType;
        "onGetCustomLandingPage"?: (event: CustomEvent<any>) => void;
        "onGetHistoryType"?: (event: CustomEvent<any>) => void;
        "onNeedRoutes"?: (event: CustomEvent<any>) => void;
        "routesItems"?: MenuItem[];
    }
    interface PskBreadcrumbNavigator {
        "eventName"?: string | null;
        "segments"?: BreadcrumbSegment[];
    }
    interface PskButton {
        "buttonClass"?: string | null;
        "disabled"?: string | boolean;
        "doubleClickEventName"?: string | null;
        "eventData"?: any | null;
        "eventDispatcher"?: string | null;
        "eventName"?: string | null;
        "label"?: string | null;
        "touchEventName"?: string | null;
        "type"?: string;
    }
    interface PskButtonGroup {
        "classes"?: string | null;
        "icon"?: string | null;
        "iconColor"?: string | null;
        "label"?: string | null;
        "opened"?: boolean;
    }
    interface PskButtonLink {
        "eventData"?: any | null;
        "eventDispatcher"?: string | null;
        "eventName"?: string | null;
        "icon"?: string;
        "name"?: string;
        "page"?: string;
    }
    interface PskCard {
        "id"?: string;
        "title"?: string;
    }
    interface PskCondition {
        "condition"?: any | null;
        "onGetModelEvent"?: (event: CustomEvent<any>) => void;
    }
    interface PskContainer {
        "controllerName"?: string | null;
        "history"?: RouterHistory;
        "htmlFilePath"?: string | null;
        "parentCallback"?: Function | null;
    }
    interface PskControllerDescriptor {
        "title"?: string;
    }
    interface PskDefaultRenderer {
        "disableSidebar"?: boolean;
        "mobileLayout"?: boolean;
        "onGetAppVersion"?: (event: CustomEvent<any>) => void;
    }
    interface PskDetails {
        "eventData"?: any | null;
        "eventDispatcher"?: string | null;
        "eventName"?: string | null;
        "layout"?: string;
        "opened"?: boolean;
        "title"?: string;
    }
    interface PskEcho {
        "value"?: string | null;
    }
    interface PskEventDescriptor {
        "title"?: string;
    }
    interface PskExample {
        "title"?: string;
    }
    interface PskForEach {
        "dataViewModel"?: string | null;
        "onGetModelEvent"?: (event: CustomEvent<any>) => void;
    }
    interface PskGrid {
        "columns"?: number | null;
        "layout"?: string | null;
    }
    interface PskLayout {
        "alignContent"?: string | null;
        "alignContentX"?: string | null;
        "alignContentY"?: string | null;
        "alignItems"?: string | null;
        "alignItemsX"?: string | null;
        "alignItemsY"?: string | null;
        "autoColumns"?: string | null;
        "autoFlow"?: string | null;
        "autoRows"?: string | null;
        "columnGap"?: string | null;
        "columns"?: number | null;
        "gap"?: string | null;
        "rowGap"?: string | null;
        "rows"?: number | null;
        "templateColumns"?: string | null;
        "templateRows"?: string | null;
    }
    interface PskLayoutItem {
        "align"?: string | null;
        "alignX"?: string | null;
        "alignY"?: string | null;
        "column"?: string | null;
        "columnEnd"?: string | null;
        "columnStart"?: string | null;
        "row"?: string | null;
        "rowEnd"?: string | null;
        "rowStart"?: string | null;
    }
    interface PskLink {
        "chapter"?: string;
        "onGetTags"?: (event: CustomEvent<any>) => void;
        "onValidateUrl"?: (event: CustomEvent<any>) => void;
        "page"?: string;
        "tag"?: string;
    }
    interface PskList {
        "listType"?: string;
    }
    interface PskMenuItemRenderer {
        "active"?: boolean;
        "historyType"?: ExtendedHistoryType;
        "onMenuClicked"?: (event: CustomEvent<any>) => void;
        "value"?: MenuItem;
    }
    interface PskMobile {
        "controllerName"?: string | null;
        "disableHeader"?: boolean;
        "disableSidebar"?: boolean;
        "enableBack"?: boolean;
        "history"?: RouterHistory;
        "title"?: string;
    }
    interface PskPage {
        "badgeBackgroundColor"?: string;
        "badgeText"?: string;
        "badgeTextColor"?: string;
        "hasToc"?: boolean;
        "navigationTitle"?: string;
        "pageClass"?: string;
        "subTitle"?: string;
        "title"?: string;
        "tocTitle"?: string;
    }
    interface PskPageLoader {
        "pageUrl"?: string;
        "type"?: string;
    }
    interface PskPageNotFound {
        "basePath"?: string;
        "pageRenderer"?: string;
        "urlDestination"?: string;
    }
    interface PskPageNotFoundRenderer {
    }
    interface PskPropertyDescriptor {
        "title"?: string;
    }
    interface PskRouteRedirect {
        "history"?: RouterHistory;
        "url"?: any;
    }
    interface PskSsapp {
        "appName"?: string;
        "history"?: RouterHistory;
        "landingPath"?: string;
        "match"?: MatchResults;
        "params"?: string;
        "seed"?: string;
    }
    interface PskStyle {
        "src"?: string | null;
    }
    interface PskUserProfile {
        "onGetUserInfo"?: (event: CustomEvent<any>) => void;
        "profileRenderer"?: any;
        "userInfo"?: any;
    }
    interface PskUserProfileRenderer {
        "userInfo"?: any;
    }
    interface QueryPageLink {
        "activeClass"?: string;
        "anchorClass"?: string;
        "anchorId"?: string;
        "anchorRole"?: string;
        "anchorTabIndex"?: string;
        "anchorTitle"?: string;
        "ariaHaspopup"?: string;
        "ariaLabel"?: string;
        "ariaPosinset"?: string;
        "ariaSetsize"?: number;
        /**
          * Custom tag to use instead of an anchor
         */
        "custom"?: string;
        "exact"?: boolean;
        "history"?: RouterHistory;
        "location"?: LocationSegments;
        "strict"?: boolean;
        "url"?: string;
        "urlMatch"?: string;
    }
    interface QueryPagesRouter {
        "history"?: RouterHistory;
        "location"?: LocationSegments;
        "pages"?: MenuItem[];
        "redirectTo"?: string;
    }
    interface SidebarRenderer {
        "active"?: boolean;
        "historyType"?: ExtendedHistoryType;
        "value"?: MenuItem;
    }
    interface IntrinsicElements {
        "dropdown-renderer": DropdownRenderer;
        "event-expandable-renderer": EventExpandableRenderer;
        "expandable-renderer": ExpandableRenderer;
        "mobile-profile-renderer": MobileProfileRenderer;
        "psk-app-menu": PskAppMenu;
        "psk-app-root": PskAppRoot;
        "psk-app-router": PskAppRouter;
        "psk-breadcrumb-navigator": PskBreadcrumbNavigator;
        "psk-button": PskButton;
        "psk-button-group": PskButtonGroup;
        "psk-button-link": PskButtonLink;
        "psk-card": PskCard;
        "psk-condition": PskCondition;
        "psk-container": PskContainer;
        "psk-controller-descriptor": PskControllerDescriptor;
        "psk-default-renderer": PskDefaultRenderer;
        "psk-details": PskDetails;
        "psk-echo": PskEcho;
        "psk-event-descriptor": PskEventDescriptor;
        "psk-example": PskExample;
        "psk-for-each": PskForEach;
        "psk-grid": PskGrid;
        "psk-layout": PskLayout;
        "psk-layout-item": PskLayoutItem;
        "psk-link": PskLink;
        "psk-list": PskList;
        "psk-menu-item-renderer": PskMenuItemRenderer;
        "psk-mobile": PskMobile;
        "psk-page": PskPage;
        "psk-page-loader": PskPageLoader;
        "psk-page-not-found": PskPageNotFound;
        "psk-page-not-found-renderer": PskPageNotFoundRenderer;
        "psk-property-descriptor": PskPropertyDescriptor;
        "psk-route-redirect": PskRouteRedirect;
        "psk-ssapp": PskSsapp;
        "psk-style": PskStyle;
        "psk-user-profile": PskUserProfile;
        "psk-user-profile-renderer": PskUserProfileRenderer;
        "query-page-link": QueryPageLink;
        "query-pages-router": QueryPagesRouter;
        "sidebar-renderer": SidebarRenderer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dropdown-renderer": LocalJSX.DropdownRenderer & JSXBase.HTMLAttributes<HTMLDropdownRendererElement>;
            "event-expandable-renderer": LocalJSX.EventExpandableRenderer & JSXBase.HTMLAttributes<HTMLEventExpandableRendererElement>;
            "expandable-renderer": LocalJSX.ExpandableRenderer & JSXBase.HTMLAttributes<HTMLExpandableRendererElement>;
            "mobile-profile-renderer": LocalJSX.MobileProfileRenderer & JSXBase.HTMLAttributes<HTMLMobileProfileRendererElement>;
            "psk-app-menu": LocalJSX.PskAppMenu & JSXBase.HTMLAttributes<HTMLPskAppMenuElement>;
            "psk-app-root": LocalJSX.PskAppRoot & JSXBase.HTMLAttributes<HTMLPskAppRootElement>;
            "psk-app-router": LocalJSX.PskAppRouter & JSXBase.HTMLAttributes<HTMLPskAppRouterElement>;
            "psk-breadcrumb-navigator": LocalJSX.PskBreadcrumbNavigator & JSXBase.HTMLAttributes<HTMLPskBreadcrumbNavigatorElement>;
            "psk-button": LocalJSX.PskButton & JSXBase.HTMLAttributes<HTMLPskButtonElement>;
            "psk-button-group": LocalJSX.PskButtonGroup & JSXBase.HTMLAttributes<HTMLPskButtonGroupElement>;
            "psk-button-link": LocalJSX.PskButtonLink & JSXBase.HTMLAttributes<HTMLPskButtonLinkElement>;
            "psk-card": LocalJSX.PskCard & JSXBase.HTMLAttributes<HTMLPskCardElement>;
            "psk-condition": LocalJSX.PskCondition & JSXBase.HTMLAttributes<HTMLPskConditionElement>;
            "psk-container": LocalJSX.PskContainer & JSXBase.HTMLAttributes<HTMLPskContainerElement>;
            "psk-controller-descriptor": LocalJSX.PskControllerDescriptor & JSXBase.HTMLAttributes<HTMLPskControllerDescriptorElement>;
            "psk-default-renderer": LocalJSX.PskDefaultRenderer & JSXBase.HTMLAttributes<HTMLPskDefaultRendererElement>;
            "psk-details": LocalJSX.PskDetails & JSXBase.HTMLAttributes<HTMLPskDetailsElement>;
            "psk-echo": LocalJSX.PskEcho & JSXBase.HTMLAttributes<HTMLPskEchoElement>;
            "psk-event-descriptor": LocalJSX.PskEventDescriptor & JSXBase.HTMLAttributes<HTMLPskEventDescriptorElement>;
            "psk-example": LocalJSX.PskExample & JSXBase.HTMLAttributes<HTMLPskExampleElement>;
            "psk-for-each": LocalJSX.PskForEach & JSXBase.HTMLAttributes<HTMLPskForEachElement>;
            "psk-grid": LocalJSX.PskGrid & JSXBase.HTMLAttributes<HTMLPskGridElement>;
            "psk-layout": LocalJSX.PskLayout & JSXBase.HTMLAttributes<HTMLPskLayoutElement>;
            "psk-layout-item": LocalJSX.PskLayoutItem & JSXBase.HTMLAttributes<HTMLPskLayoutItemElement>;
            "psk-link": LocalJSX.PskLink & JSXBase.HTMLAttributes<HTMLPskLinkElement>;
            "psk-list": LocalJSX.PskList & JSXBase.HTMLAttributes<HTMLPskListElement>;
            "psk-menu-item-renderer": LocalJSX.PskMenuItemRenderer & JSXBase.HTMLAttributes<HTMLPskMenuItemRendererElement>;
            "psk-mobile": LocalJSX.PskMobile & JSXBase.HTMLAttributes<HTMLPskMobileElement>;
            "psk-page": LocalJSX.PskPage & JSXBase.HTMLAttributes<HTMLPskPageElement>;
            "psk-page-loader": LocalJSX.PskPageLoader & JSXBase.HTMLAttributes<HTMLPskPageLoaderElement>;
            "psk-page-not-found": LocalJSX.PskPageNotFound & JSXBase.HTMLAttributes<HTMLPskPageNotFoundElement>;
            "psk-page-not-found-renderer": LocalJSX.PskPageNotFoundRenderer & JSXBase.HTMLAttributes<HTMLPskPageNotFoundRendererElement>;
            "psk-property-descriptor": LocalJSX.PskPropertyDescriptor & JSXBase.HTMLAttributes<HTMLPskPropertyDescriptorElement>;
            "psk-route-redirect": LocalJSX.PskRouteRedirect & JSXBase.HTMLAttributes<HTMLPskRouteRedirectElement>;
            "psk-ssapp": LocalJSX.PskSsapp & JSXBase.HTMLAttributes<HTMLPskSsappElement>;
            "psk-style": LocalJSX.PskStyle & JSXBase.HTMLAttributes<HTMLPskStyleElement>;
            "psk-user-profile": LocalJSX.PskUserProfile & JSXBase.HTMLAttributes<HTMLPskUserProfileElement>;
            "psk-user-profile-renderer": LocalJSX.PskUserProfileRenderer & JSXBase.HTMLAttributes<HTMLPskUserProfileRendererElement>;
            "query-page-link": LocalJSX.QueryPageLink & JSXBase.HTMLAttributes<HTMLQueryPageLinkElement>;
            "query-pages-router": LocalJSX.QueryPagesRouter & JSXBase.HTMLAttributes<HTMLQueryPagesRouterElement>;
            "sidebar-renderer": LocalJSX.SidebarRenderer & JSXBase.HTMLAttributes<HTMLSidebarRendererElement>;
        }
    }
}
